"use client"
import { useEffect, useState } from "react"

type Department={id:string;name:string;subjects:{id:string;name:string}[]}; type Class={id:string;name:string;gradeLevel:number}
export default function TestsManager({departments,classes}:{departments:Department[];classes:Class[]}){
 const [name,setName]=useState("");const [departmentId,setDepartmentId]=useState("");const [subjectId,setSubjectId]=useState("");const [classId,setClassId]=useState("");const [date,setDate]=useState("");const [max,setMax]=useState("");const [term,setTerm]=useState("term1");const [loading,setLoading]=useState(false);const subjects=departments.find(d=>d.id===departmentId)?.subjects??[]
 async function save(){if(!name||!subjectId||!classId||!date||!max)return;setLoading(true);try{const r=await fetch('/api/tests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,subjectId,classId,testDate:date,maxScore:max,term})});const d=await r.json();if(!r.ok)throw Error(d.error);location.reload()}catch(e){alert(e instanceof Error?e.message:'Failed')}finally{setLoading(false)}}
 return <section className="rounded-lg border bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Create Test</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><input className="rounded border px-3 py-2" placeholder="Test name" value={name} onChange={e=>setName(e.target.value)}/><select className="rounded border px-3 py-2" value={departmentId} onChange={e=>{setDepartmentId(e.target.value);setSubjectId('')}}><option value="">Department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><select className="rounded border px-3 py-2" value={subjectId} onChange={e=>setSubjectId(e.target.value)} disabled={!departmentId}><option value="">Subject</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select className="rounded border px-3 py-2" value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="date" className="rounded border px-3 py-2" value={date} onChange={e=>setDate(e.target.value)}/><input type="number" min="1" className="rounded border px-3 py-2" placeholder="Maximum score" value={max} onChange={e=>setMax(e.target.value)}/><select className="rounded border px-3 py-2" value={term} onChange={e=>setTerm(e.target.value)}><option value="term1">Term 1</option><option value="term2">Term 2</option><option value="term3">Term 3</option></select></div><button onClick={save} disabled={loading} className="mt-4 rounded bg-black px-4 py-2 text-white">{loading?'Saving...':'Create Test'}</button></section>
}
